### ISSUE TITLE
Bug in bbq.php

### ISSUE THREAD

**Issue by produktive** [eightywon/maverick#2]
If you start a cook from device1 (phone) and then access bbq.php from any device besides device1, you will not get any data. This is happening because it relies on a cookie to see if there is an active cook. The cookie will only be stored on the device that the cook was started from. I propose instead that you query the db for table "activecook" and see what number it holds. If it is "-1" then there is no active cook. If there is a positive integer, it corresponds with the current cookid.

```
$active=Database::selectSingle("select cookid from activecook order by cookid desc limit 1;",$pdo);
$cookID=$active['cookid'];
if ($cookID > -1) {
	$single=Database::selectSingle("select probe1,probe2,time from readings where cookid=".$cookID." order by time desc limit 1;",$pdo);
	$probe1=$single['probe1'];
	$probe2=$single['probe2'];
	$time=$single['time'];
}
```

I have tested this code and it works.

**Comment by eightywon** [comment]
Agreed. I'm hoping to fix this with the front end redesign.
