### ISSUE TITLE
Occasional outlier datapoints

### ISSUE THREAD

**Issue by produktive** [eightywon/maverick#4]
Sometimes if the Pi is near the outer edge of the transmitter radius, or for no reason, it will record bogus data points. I'll see the grill temperature record a data point with 1,000 - 4,000 degrees when obviously that not possible or maybe even a 0. However, most of the data will be accurate save for a dozen or two points during a long cook. I assume this is why you created the delete function. However instead of having to delete a couple dozen data points what if you integrated a setting that controls a min/max tolerance setting. It will basically throw out any data that is over the max and under the min and not record them in the first place. You can set this value on a settings page or on the start page. It should save in the db so you don't have to set it every time from cook to cook.

**Comment by eightywon** [comment]
I've done some filtering inside maverick.c but I agree, it doesn't catch all those extremes. I agree, this is a good idea I'll eventually implement (if I can't do a better job of filtering out the garbage while interpreting the actual signal).

I started some work on calculating/validating the checksum the Maverick transmits along with the temp data, but just haven't gotten back to that. Finishing that work would obviously allow us to just discard anything that has a bad checksum.

**Comment by produktive** [comment]
I forked a version of your project which now takes care of this during the graph display. Check it out if you'd like, otherwise your checksum method is likely better
