### ISSUE TITLE
Verify that this works with Maverick XR-50 

### ISSUE THREAD

**Issue by Jeager2** [eightywon/maverick#6]
The updated version of the 732 is the XR-50 and seems to use the same probes.
I have both a 732 and XR-50 and will test to make sure it works. 
I tested several months ago briefly and it failed, however I did not have a 732 at the time to verify that the code was working at all.
I would like to work with you to get the XR-50 working/tested.

https://www.maverickthermometers.com/product/xr-50/

**Comment by Jeager2** [comment]
I found the fcc document: 
http://www.fcc.io/2AATP-XR50
Looks like it won't work... Am I wrong ???

Transmit Frequency:915MHz
Number of Channels:1
Modulation Type:FSKAntenna 
Description:InternalAntenna, 0dBi(Max.)

**Comment by eightywon** [comment]
You're not wrong. Different frequency so the receiver won't pick up the signal. Very possible that there will be protocol differences too even if you got a 915mhz receiver module going.
