### ISSUE TITLE
New maverick.c is broken

### ISSUE THREAD

**Issue by produktive** [eightywon/maverick#8]
I recently came back to this project after a while and noticed there has been an update to the code maverick.c since I last used it in 2018. I recompiled the new file, and after running it I notice that my device is no longer capturing any probe temperature data. It's possible that somehow my 433 mhz receiver failed at some point since I last used the device 6 months ago but it seems unlikely? Have you confirmed that the maverick.c works as intended, and if so, do you know of I way I can test to see if my 433mhz rf receiver is functioning?

**Comment by produktive** [comment]
So to follow-up here, the newest maverick.c file is a breaking change. I ordered new RF chips, new protoboard, thinking that my RF chip went bad. Still doesn't work. I reverted my maverick.c file to the one I had in 2018, and it works again. Do not use the newest maverick.c! Your device will not record any temperature data. I ruined my protoboard for nothing.

**Comment by eightywon** [comment]
the latest version (which is still like 4 years stale at this point) of the code uses PIGPIO for interfacing with some of the GPIO pins (I can't remember why I changed it, it's been a long time since I've used or worked on this)

try reinstalling, following the directions in the updated readme starting with around #10. It was tested and working with the version of raspbian available at the time (stretch lite, March 2018)

**Comment by produktive** [comment]
I guess I just don't really understand the reason for the pin change, which occurred on [May 14, 2018](https://github.com/eightywon/maverick/commit/541dd51cf8535b99694c664bf91f38dda4504377). That was after pigpio was implemented, you changed it from 16 to 15 when you changed from wiringPi to pigpio. But then 2 weeks later, you switched from 15 to 6. I am wondering if that is a breaking change. I'm going to test it out by changing it back.

**Comment by produktive** [comment]
Changing the PIN from 6 to 15 made it work again. After investigating, I think you were looking at the GPIO breakout diagram upside down. That would correspond to you selecting 6 instead of 15. [image](https://user-images.githubusercontent.com/21110476/202484669-f551f328-66bf-4ca8-8e01-bb3c507ac1cc.png)
